### ISSUE TITLE
Neues Projekt: Zufällige Namen generieren

### ISSUE THREAD

**Issue by sascha-henger** [sascha-henger/ausbildungs-repository#7]
Es soll ein Projekt geben, mit dem man zufällige Namen generieren kann.
Zunächst eine einfache Anwedung mit einer Funktion, die einem jedes mal einen zufällig generierten Namen erzeugt, z.B.

GetRandomName() -> Thomas Roberts
GetRandomName() -> Rupert Roosevelt
GetRandomName() -> Madelene Yu

usw.

**Comment by RRieck** [comment]
Ist eingebaut ;)
