### ISSUE TITLE
Erweiterung: Zufällige Personen statt nur Namen

### ISSUE THREAD

**Issue by sascha-henger** [sascha-henger/ausbildungs-repository#8]
Eine weitere Funktion soll ganze Personen erzeugen, z.B.: 

GetRandomPerson() ->
{
    FirstName: "Wilma",
    LastName: "Brown",
    Birthday: "2001-8-6",
    Birthplace: "Lodz",
}

**Comment by RRieck** [comment]
Auch erledigt
